#!/bin/bash

source /opt/autolabor/ros/catkin_ws/devel/setup.bash
IP=`ifconfig wlan0 | grep "inet 地址:" | awk '{print $2}' | cut -c 8-`

if [ -z "$IP" ]; then
  IP="127.0.0.1"
fi

export ROS_MASTER_URI=http://$IP:11311/
export ROS_IP=$IP

nohup roslaunch zed_wrapper zed2.launch&
sleep 5
zenity --no-wrap --info --text="查看图像中有点云出现，Zed正常，否则检查Zed连接，点确定后再次尝试"
killall rosmaster


