(cl:defpackage path_server-srv
  (:use )
  (:export
   "SETPATHNAME"
   "<SETPATHNAME-REQUEST>"
   "SETPATHNAME-REQUEST"
   "<SETPATHNAME-RESPONSE>"
   "SETPATHNAME-RESPONSE"
   "SETPHOTOPOINT"
   "<SETPHOTOPOINT-REQUEST>"
   "SETPHOTOPOINT-REQUEST"
   "<SETPHOTOPOINT-RESPONSE>"
   "SETPHOTOPOINT-RESPONSE"
   "SETPOINTNAME"
   "<SETPOINTNAME-REQUEST>"
   "SETPOINTNAME-REQUEST"
   "<SETPOINTNAME-RESPONSE>"
   "SETPOINTNAME-RESPONSE"
  ))

