// Generated by gencpp from file path_server/SetPhotoPointRequest.msg
// DO NOT EDIT!


#ifndef PATH_SERVER_MESSAGE_SETPHOTOPOINTREQUEST_H
#define PATH_SERVER_MESSAGE_SETPHOTOPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_server
{
template <class ContainerAllocator>
struct SetPhotoPointRequest_
{
  typedef SetPhotoPointRequest_<ContainerAllocator> Type;

  SetPhotoPointRequest_()
    : id(0)
    , x(0.0)
    , y(0.0)
    , yaw(0.0)  {
    }
  SetPhotoPointRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , x(0.0)
    , y(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _id_type;
  _id_type id;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::path_server::SetPhotoPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_server::SetPhotoPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPhotoPointRequest_

typedef ::path_server::SetPhotoPointRequest_<std::allocator<void> > SetPhotoPointRequest;

typedef boost::shared_ptr< ::path_server::SetPhotoPointRequest > SetPhotoPointRequestPtr;
typedef boost::shared_ptr< ::path_server::SetPhotoPointRequest const> SetPhotoPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_server::SetPhotoPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_server::SetPhotoPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_server::SetPhotoPointRequest_<ContainerAllocator1> & lhs, const ::path_server::SetPhotoPointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_server::SetPhotoPointRequest_<ContainerAllocator1> & lhs, const ::path_server::SetPhotoPointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::path_server::SetPhotoPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_server::SetPhotoPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_server::SetPhotoPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_server::SetPhotoPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_server::SetPhotoPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_server::SetPhotoPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_server::SetPhotoPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4a0898a68886791d7b84a9f35d84726";
  }

  static const char* value(const ::path_server::SetPhotoPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4a0898a68886791ULL;
  static const uint64_t static_value2 = 0xd7b84a9f35d84726ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_server::SetPhotoPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_server/SetPhotoPointRequest";
  }

  static const char* value(const ::path_server::SetPhotoPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_server::SetPhotoPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 id\n"
"float64 x\n"
"float64 y\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::path_server::SetPhotoPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_server::SetPhotoPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPhotoPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_server::SetPhotoPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_server::SetPhotoPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_SERVER_MESSAGE_SETPHOTOPOINTREQUEST_H
