// Generated by gencpp from file path_server/SetPointName.msg
// DO NOT EDIT!


#ifndef PATH_SERVER_MESSAGE_SETPOINTNAME_H
#define PATH_SERVER_MESSAGE_SETPOINTNAME_H

#include <ros/service_traits.h>


#include <path_server/SetPointNameRequest.h>
#include <path_server/SetPointNameResponse.h>


namespace path_server
{

struct SetPointName
{

typedef SetPointNameRequest Request;
typedef SetPointNameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPointName
} // namespace path_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_server::SetPointName > {
  static const char* value()
  {
    return "0e0e3778202d80927ca53f4e1bc7f936";
  }

  static const char* value(const ::path_server::SetPointName&) { return value(); }
};

template<>
struct DataType< ::path_server::SetPointName > {
  static const char* value()
  {
    return "path_server/SetPointName";
  }

  static const char* value(const ::path_server::SetPointName&) { return value(); }
};


// service_traits::MD5Sum< ::path_server::SetPointNameRequest> should match
// service_traits::MD5Sum< ::path_server::SetPointName >
template<>
struct MD5Sum< ::path_server::SetPointNameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_server::SetPointName >::value();
  }
  static const char* value(const ::path_server::SetPointNameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_server::SetPointNameRequest> should match
// service_traits::DataType< ::path_server::SetPointName >
template<>
struct DataType< ::path_server::SetPointNameRequest>
{
  static const char* value()
  {
    return DataType< ::path_server::SetPointName >::value();
  }
  static const char* value(const ::path_server::SetPointNameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_server::SetPointNameResponse> should match
// service_traits::MD5Sum< ::path_server::SetPointName >
template<>
struct MD5Sum< ::path_server::SetPointNameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_server::SetPointName >::value();
  }
  static const char* value(const ::path_server::SetPointNameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_server::SetPointNameResponse> should match
// service_traits::DataType< ::path_server::SetPointName >
template<>
struct DataType< ::path_server::SetPointNameResponse>
{
  static const char* value()
  {
    return DataType< ::path_server::SetPointName >::value();
  }
  static const char* value(const ::path_server::SetPointNameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_SERVER_MESSAGE_SETPOINTNAME_H
