// Generated by gencpp from file path_server/SetPhotoPoint.msg
// DO NOT EDIT!


#ifndef PATH_SERVER_MESSAGE_SETPHOTOPOINT_H
#define PATH_SERVER_MESSAGE_SETPHOTOPOINT_H

#include <ros/service_traits.h>


#include <path_server/SetPhotoPointRequest.h>
#include <path_server/SetPhotoPointResponse.h>


namespace path_server
{

struct SetPhotoPoint
{

typedef SetPhotoPointRequest Request;
typedef SetPhotoPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPhotoPoint
} // namespace path_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_server::SetPhotoPoint > {
  static const char* value()
  {
    return "c4a0898a68886791d7b84a9f35d84726";
  }

  static const char* value(const ::path_server::SetPhotoPoint&) { return value(); }
};

template<>
struct DataType< ::path_server::SetPhotoPoint > {
  static const char* value()
  {
    return "path_server/SetPhotoPoint";
  }

  static const char* value(const ::path_server::SetPhotoPoint&) { return value(); }
};


// service_traits::MD5Sum< ::path_server::SetPhotoPointRequest> should match
// service_traits::MD5Sum< ::path_server::SetPhotoPoint >
template<>
struct MD5Sum< ::path_server::SetPhotoPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_server::SetPhotoPoint >::value();
  }
  static const char* value(const ::path_server::SetPhotoPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_server::SetPhotoPointRequest> should match
// service_traits::DataType< ::path_server::SetPhotoPoint >
template<>
struct DataType< ::path_server::SetPhotoPointRequest>
{
  static const char* value()
  {
    return DataType< ::path_server::SetPhotoPoint >::value();
  }
  static const char* value(const ::path_server::SetPhotoPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_server::SetPhotoPointResponse> should match
// service_traits::MD5Sum< ::path_server::SetPhotoPoint >
template<>
struct MD5Sum< ::path_server::SetPhotoPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_server::SetPhotoPoint >::value();
  }
  static const char* value(const ::path_server::SetPhotoPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_server::SetPhotoPointResponse> should match
// service_traits::DataType< ::path_server::SetPhotoPoint >
template<>
struct DataType< ::path_server::SetPhotoPointResponse>
{
  static const char* value()
  {
    return DataType< ::path_server::SetPhotoPoint >::value();
  }
  static const char* value(const ::path_server::SetPhotoPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_SERVER_MESSAGE_SETPHOTOPOINT_H
