// Generated by gencpp from file path_server/SetPointNameRequest.msg
// DO NOT EDIT!


#ifndef PATH_SERVER_MESSAGE_SETPOINTNAMEREQUEST_H
#define PATH_SERVER_MESSAGE_SETPOINTNAMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_server
{
template <class ContainerAllocator>
struct SetPointNameRequest_
{
  typedef SetPointNameRequest_<ContainerAllocator> Type;

  SetPointNameRequest_()
    : point_name()  {
    }
  SetPointNameRequest_(const ContainerAllocator& _alloc)
    : point_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _point_name_type;
  _point_name_type point_name;





  typedef boost::shared_ptr< ::path_server::SetPointNameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_server::SetPointNameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPointNameRequest_

typedef ::path_server::SetPointNameRequest_<std::allocator<void> > SetPointNameRequest;

typedef boost::shared_ptr< ::path_server::SetPointNameRequest > SetPointNameRequestPtr;
typedef boost::shared_ptr< ::path_server::SetPointNameRequest const> SetPointNameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_server::SetPointNameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_server::SetPointNameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_server::SetPointNameRequest_<ContainerAllocator1> & lhs, const ::path_server::SetPointNameRequest_<ContainerAllocator2> & rhs)
{
  return lhs.point_name == rhs.point_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_server::SetPointNameRequest_<ContainerAllocator1> & lhs, const ::path_server::SetPointNameRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::path_server::SetPointNameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_server::SetPointNameRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_server::SetPointNameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_server::SetPointNameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_server::SetPointNameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_server::SetPointNameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_server::SetPointNameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e0e3778202d80927ca53f4e1bc7f936";
  }

  static const char* value(const ::path_server::SetPointNameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e0e3778202d8092ULL;
  static const uint64_t static_value2 = 0x7ca53f4e1bc7f936ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_server::SetPointNameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_server/SetPointNameRequest";
  }

  static const char* value(const ::path_server::SetPointNameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_server::SetPointNameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string point_name\n"
;
  }

  static const char* value(const ::path_server::SetPointNameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_server::SetPointNameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPointNameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_server::SetPointNameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_server::SetPointNameRequest_<ContainerAllocator>& v)
  {
    s << indent << "point_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.point_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_SERVER_MESSAGE_SETPOINTNAMEREQUEST_H
